<?php

// We need the referral_send_email module's hook_userpoints to run after the userpoints_extend_role module's version. 

if (module_exists('userpoints_extend_role'))
{
  $weight = db_query("SELECT weight FROM {system} WHERE type = 'module' AND name = 'userpoints_extend_role'")->fetchField();
  db_query("UPDATE {system} SET weight = :weight WHERE type = 'module' AND name = 'referral_send_email'", 
    array(':weight' => $weight+5));
}
?>

